apiVersion: v2
appVersion: v0.0.20
description: A helm chart for AppsCode license-proxyserver user roles
home: https://github.com/appscode-cloud/license-proxyserver
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
maintainers:
- email: support@appscode.com
  name: appscode
name: license-proxyserver-user-roles
sources:
- https://github.com/appscode-cloud/license-proxyserver
type: application
version: v2025.1.17
