apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubestash-operator.fullname" . }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["get", "create", "patch", "update"]
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["*"]
  - apiGroups:
      - core.kubestash.com
      - kubedb.com
      - snapshot.storage.k8s.io
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - storage.kubestash.com
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - appcatalog.appscode.com
    resources:
      - "*"
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - config.kubestash.com
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - addons.kubestash.com
    resources:
      - "*"
    verbs: [ "*" ]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ["create"]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch", "create"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["get", "list", "watch","create"]
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs: ["create"]
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: ["get", "list", "create", "patch", "watch", "delete"]
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs: ["get", "create"]
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
      - rolebindings
      - clusterrolebindings
    verbs: ["get","list", "watch", "create", "delete", "patch", "update"]
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs: ["get","delete"]
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - catalog.kubedb.com
    resources:
      - elasticsearchs
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - appcatalog.appscode.com
    resources:
      - appbindings
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - elasticsearch.kubedb.com
    resources:
      - elasticsearchdashboards
    verbs: ["list"]
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs: [ "get", "create"]
  - apiGroups:
      - archiver.kubedb.com
    resources:
      - "*"
    verbs: [ "get", "create" ]

