apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubestash
  namespace: argocd
spec:
  destination:
    namespace: kubestash
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/kubestash/base
    repoURL: https://github.com/tamalsaha/learn-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
