{{- if dig "ace" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:ace:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - appreleases
  verbs: ["create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:ace:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - appreleases
  verbs: ["get", "list", "watch"]

{{- end }}
