apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-catalog
  namespace: argocd
spec:
  project: default
  source:
    chart: kubedb-catalog
    repoURL: https://charts.appscode.com/stable
    # targetRevision: v2021.11.24
    targetRevision: v2022.03.28
    # helm:
    #   releaseName: kubedb-catalog
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubedb
  syncPolicy:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - FailOnSharedResource=true
      # - RespectIgnoreDifferences=true
