apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-catalog
  namespace: argocd
spec:
  project: default
  source:
    # path: charts/kubedb-catalog
    # repoURL: https://github.com/kubedb/installer
    # # targetRevision: release-v2021.11.24
    # targetRevision: release-v2022.03.28

    chart: kubedb-catalog
    repoURL: https://charts.appscode.com/stable
    # targetRevision: v2021.11.24
    targetRevision: v2022.03.28
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubedb
  syncPolicy:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:
      prune: true
      selfHeal: true
      # allowEmpty: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
      - CreateNamespace=true
      # needed to avoid Sync Fail when CRD updates
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      # - Replace=true
      # - PrunePropagationPolicy=foreground
      # - PruneLast=true
      # - RespectIgnoreDifferences=true
