apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns-stash.yaml

helmCharts:
# old stash
- name: stash
  includeCRDs: true
  valuesInline:
    ace-user-roles:
      enabled: false
    features:
      enterprise: true
  releaseName: stash
  namespace: stash
  version: v2025.2.10
  repo: oci://ghcr.io/appscode-charts
