# Default values for ace-user-roles.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

enableClusterRoles:
  ace: true
  appcatalog: true
  catalog: true
  cert-manager: true
  kubedb: true
  kubedb-ui: true
  kubestash: true
  kubevault: true
  license-proxyserver: true
  metrics: true
  prometheus: true
  stash: true

annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-delete-policy": before-hook-creation
