apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  name: kubestash-appscode-com-repository
spec:
  targetRef:
    apiVersion: storage.kubestash.com/v1alpha1
    kind: Repository
  commonLabels:
  - key: invoker_kind
    value: "Repository"
  - key: invoker_name
    valuePath: .metadata.name
  - key: target_kind
    valuePath: .spec.appRef.kind
  - key: target_name
    valuePath: .spec.appRef.name
  - key: target_namespace
    valuePath: .spec.appRef.namespace
  metrics:
  - name: created
    help: "Unix creation timestamp of this Repository object"
    type: gauge
    field:
      path: .metadata.creationTimestamp
      type: DateTime
    metricValue:
      valueFromPath: .metadata.creationTimestamp
  - name: info
    help: "General information about this Repository"
    type: gauge
    labels:
    - key: path
      valuePath: .spec.path
    - key: phase
      valuePath: .status.phase
    - key: integrity
      valuePath: .status.integrity
    metricValue:
      value: 1
  - name: last_successful_backup
    help: "Last successful backup stored in this Repository"
    type: gauge
    field:
      path: .status.lastBackupTime
      type: DateTime
    metricValue:
      valueFromPath: .status.lastBackupTime
  - name: size_bytes
    help: "Total backed up data stored in this Repository"
    type: gauge
    field:
      path: .status.size
      type: String
    params:
    - key: size
      valuePath: .status.size
    metricValue:
      valueFromExpression: "bytes(size)"
  - name: snapshot_count_total
    help: "Number of current snapshots stored in this Repository"
    type: gauge
    field:
      path: .status.snapshotCount
      type: Integer
    metricValue:
      valueFromPath: .status.snapshotCount
  - name: conditions
    help: "Current conditions of this Repository"
    type: gauge
    field:
      path: .status.conditions
      type: Array
    labels:
    - key: condition
      valuePath: .status.conditions[*].type
    - key: status
      valuePath: .status.conditions[*].status
    metricValue:
      value: 1

