apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns-kubedb.yaml

helmCharts:
- name: kubedb
  includeCRDs: true
  valuesInline:
    ace-user-roles:
      enabled: false
  releaseName: kubedb
  namespace: kubedb
  version: v2025.2.6-rc.0
  repo: oci://ghcr.io/appscode-charts

# patches:
# - target:
#     kind: CustomResourceDefinition
#     name: addons.addons.kubestash.com
#   patch: |-
#     - op: replace
#       path: /metadata/name
#       value: addons.addons.kubestash.com-deconflict

# # CustomResourceDefinition.v1.apiextensions.k8s.io/addons.addons.kubestash.com.[noNs]

# # - name: kubedb-kubestash-catalog
# #   includeCRDs: false
# #   releaseName: kubedb-kubestash-catalog
# #   namespace: kubedb
# #   version: v2025.2.6-rc.0
# #   repo: oci://ghcr.io/appscode-charts
