apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns-kubestash.yaml

helmCharts:
# new stash
- name: kubestash
  includeCRDs: true
  valuesInline:
    ace-user-roles:
      enabled: false
  releaseName: kubestash
  namespace: kubestash
  version: v2025.2.10
  repo: oci://ghcr.io/appscode-charts
