apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns-kubevault.yaml

helmCharts:
- name: kubevault
  includeCRDs: true
  valuesInline:
    ace-user-roles:
      enabled: false
  releaseName: kubevault
  namespace: kubevault
  version: v2025.2.10
  repo: oci://ghcr.io/appscode-charts
