{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "petset.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "petset.selectorLabels" . | nindent 6 }}
  ingress:
  - {}
  policyTypes:
  - Ingress
{{- end }}