{{ template "petset.prepare-certs" $ }}

{{- if or .Values.apiserver.enableMutatingWebhook .Values.apiserver.enableValidatingWebhook }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "petset.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ $._caCrt }}
  tls.crt: {{ $._serverCrt }}
  tls.key: {{ $._serverKey }}
{{- end }}
