{{ template "petset.prepare-certs" $ }}

{{- if .Values.apiserver.enableMutatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "petset.fullname" . }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "petset.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-k8s-appscode-com-v1-petset
      caBundle: {{ $._caCrt }}
    failurePolicy: Fail
    name: petsets.apps.k8s.appscode.com
    rules:
      - apiGroups:
          - apps.k8s.appscode.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - petsets
    sideEffects: None
{{ end }}
