{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "supervisor.fullname" . }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "supervisor.selectorLabels" . | nindent 6 }}
  egress:
  - {}
  policyTypes:
  - Egress
{{- end }}