{{- if and .Values.global .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubestash-operator.fullname" . }}-operator-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubestash-operator.selectorLabels" . | nindent 6 }}
  egress:
  # Scenarios considered:
  # - Communication with apiServer
  # - Initialize BackupStorage
  # - Calls of discovery.DiscoveryInterface from cloud providers
  - {}
  policyTypes:
  - Egress
{{- end }}
