apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  name: kubestash-appscode-com-backupconfiguration
spec:
  targetRef:
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
  commonLabels:
  - key: backup_invoker_kind
    value: "BackupConfiguration"
  - key: backup_invoker_name
    valuePath: .metadata.name
  - key: target_kind
    valuePath: .spec.target.kind
  - key: target_name
    valuePath: .spec.target.name
  - key: target_namespace
    valuePath: .spec.target.namespace
  metrics:
  - name: created
    help: "Unix creation timestamp of this BackupConfiguration object"
    type: gauge
    field:
      path: .metadata.creationTimestamp
      type: DateTime
    metricValue:
      valueFromPath: .metadata.creationTimestamp
  - name: info
    help: "General information about this BackupConfiguration"
    type: gauge
    metricValue:
      value: 1
  - name: sessions
    help: "List of sessions of this BackupConfiguration"
    type: gauge
    field:
      path: .spec.sessions
      type: Array
    labels:
    - key: session_name
      valuePath: .spec.sessions[*].name
    - key: schedule
      valuePath: .spec.sessions[*].scheduler.schedule
    - key: addon_name
      valuePath: .spec.sessions[*].addon.name
    metricValue:
      value: 1
  - name: phase
    help: "BackupConfiguration object current phase"
    type: gauge
    field:
      path: .status.phase
      type: String
    params:
    - key: phase
      valuePath: .status.phase
    states:
      labelKey: phase
      values:
      - labelValue: Ready
        metricValue:
          valueFromExpression: "int(phase == 'Ready')"
      - labelValue: NotReady
        metricValue:
          valueFromExpression: "int(phase == 'NotReady')"
      - labelValue: Invalid
        metricValue:
          valueFromExpression: "int(phase == 'Invalid')" 
  - name: conditions
    help: "Current conditions of this BackupConfiguration"
    type: gauge
    field:
      path: .status.conditions
      type: Array
    labels:
    - key: condition
      valuePath: .status.conditions[*].type
    - key: status
      valuePath: .status.conditions[*].status
    metricValue:
      value: 1

