{{- if dig "kubedb" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb:core:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - kubedb.com
  - archiver.kubedb.com
  - catalog.kubedb.com
  - elasticsearch.kubedb.com
  - kafka.kubedb.com
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb:core:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - kubedb.com
  - archiver.kubedb.com
  - elasticsearch.kubedb.com
  - kafka.kubedb.com
  resources:
  - "*"
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubedb:core:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - kubedb.com
  - archiver.kubedb.com
  - catalog.kubedb.com
  - elasticsearch.kubedb.com
  - kafka.kubedb.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]

{{- end }}
