{{- if dig "kubedb-ui" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:kubedb-ui:view
rules:
- apiGroups:
  - catalog.kubedb.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - storage.k8s.io
  resources:
  - "storageclasses"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - cert-manager.io
  resources:
  - "clusterissuers"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - node.k8s.appscode.com
  resources:
  - "nodetopologies"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - "placementpolicies"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - charts.x-helm.dev
  resources:
  - "clusterchartpresets"
  verbs: ["get", "list", "watch"]
  resourceNames:
  - "kubedb-ui-presets"
  - "stash-presets"
---

# Grant logged in users read permission on cluster scoped resources required for kubedb-ui

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appscode:kubedb-ui:view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appscode:kubedb-ui:view
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

{{- end }}
