{{- if .Values.apiserver.enableValidatingWebhook }}
{{- $caCrt := dig "data" "ca.crt" "unknown" (lookup "v1" "ConfigMap" .Release.Namespace "kube-root-ca.crt") | b64enc }}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.supervisor.appscode.com
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
webhooks:
  - name: maintenancewindows.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/validators.supervisor.appscode.com/v1alpha1/maintenancewindowwebhooks
      caBundle: {{ $caCrt }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - supervisor.appscode.com
        apiVersions:
          - "*"
        resources:
          - maintenancewindows
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    sideEffects: None

  - name: clustermaintenancewindows.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/validators.supervisor.appscode.com/v1alpha1/clustermaintenancewindowwebhooks
      caBundle: {{ $caCrt }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - supervisor.appscode.com
        apiVersions:
          - "*"
        resources:
          - clustermaintenancewindows
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    sideEffects: None

  - name: recommendations.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/validators.supervisor.appscode.com/v1alpha1/recommendationwebhooks
      caBundle: {{ $caCrt }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - supervisor.appscode.com
        apiVersions:
          - "*"
        resources:
          - recommendations
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    sideEffects: None
{{- end }}
