apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb
  namespace: argocd
spec:
  ignoreDifferences:
  - jsonPointers:
    - /data
    kind: Secret
    name: kubedb-kubedb-webhook-server-apiserver-cert
    namespace: kubedb
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations/reload
  project: default
  source:
    chart: kubedb
    repoURL: https://charts.appscode.com/stable
    targetRevision: v2021.11.24
    # targetRevision: v2022.03.28
    helm:
      releaseName: kubedb
      parameters:
      - name: kubedb-provisioner.enabled
        value: 'true'
      - name: kubedb-ops-manager.enabled
        value: 'true'
      - name: kubedb-autoscaler.enabled
        value: 'true'
      - name: kubedb-dashboard.enabled
        value: 'true'
      - name: kubedb-schema-manager.enabled
        value: 'true'
      - name: global.license
        value: |
          -----BEGIN CERTIFICATE-----
          MIIEUDCCAzigAwIBAgIIT/4d7KRU6iEwDQYJKoZIhvcNAQELBQAwJTEWMBQGA1UE
          ChMNQXBwc0NvZGUgSW5jLjELMAkGA1UEAxMCY2EwHhcNMjIwNTAzMjA1MzAxWhcN
          MjIwNjAyMjA1MzAxWjCCARgxDzANBgNVBAYTBmt1YmVkYjETMBEGA1UECBMKZW50
          ZXJwcmlzZTGBpDAXBgNVBAoTEGt1YmVkYi1jb21tdW5pdHkwFwYDVQQKExBrdWJl
          ZGItZXh0LXN0YXNoMBgGA1UEChMRa3ViZWRiLWF1dG9zY2FsZXIwGAYDVQQKExFr
          dWJlZGItZW50ZXJwcmlzZTAcBgNVBAoTFXBhbm9wdGljb24tZW50ZXJwcmlzZTAe
          BgNVBAoTF2t1YmVkYi1tb25pdG9yaW5nLWFnZW50MRowGAYDVQQLExFrdWJlZGIt
          ZW50ZXJwcmlzZTEtMCsGA1UEAxMkMjc2MDVhMTEtNTYxYi00YWE5LWJlODItNWFl
          NThmNmM2NzYwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7irOL6xb
          J9qI2cgs4JLtL32Ci0viPCfrYmCUdN/AlxE8eHfCkwoRQmt3ez0D8Q+EQwRmmpWt
          xF+ONviqA3RiWOwopXL7A4VPLa9eRr464Bw3SefilecaFlr11kdMPb9ZIAvuedYJ
          /7YbfgPsaHSamAgDll60Qkn5FrZiobey0hd/DkBHdJOJLQFg3PqaHESy6ckEh8Iy
          iZwCqu0oa0GPzwVMF8vI7m/zUQ1VDogUwQBnDlFn93syxvzcTdyCnayJsdj5XoTM
          H+pkoSqW629wYfuM0flEOwr8Z+zCweW5344yGahK7BxYeBEnrc2Oft3SRbHAlzGT
          9fAv8ePt8yiG/wIDAQABo4GOMIGLMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
          BggrBgEFBQcDAjBkBgNVHREEXTBbgiQyNzYwNWExMS01NjFiLTRhYTktYmU4Mi01
          YWU1OGY2YzY3NjCBH1RhbWFsIFNhaGEgPHRhbWFsQGFwcHNjb2RlLmNvbT6BEnRh
          bWFsQGFwcHNjb2RlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAZoa2hDA+TjzHF7Td
          xoNXBDWk4BmG1KJutZW3bAk0v9E9jh3c8C/CElma177BwPkUI93wOkaIGT7MJYtl
          bz2uiT0fxJpGeqFJwO18vSRd8/JgHrUs4zLDI7+hdH50Rdx5rcctVel86Ilcdols
          CsD1pA93AlTIF7mUWywA6w9KBOzx3mtiPcQD73U4Fw32oyFXwNQZvufkxf+pECeE
          2Cs33KSBmqadnZ+Av95/IB3jXAyCEK5YxwHPR2SB6vnJ7ztmDaO3M44+0aNl7Ctd
          S+V18Si91tv855UudhkSfOhwi+O6Q8M0vmlGd6N/TdM/8ndMrITpwvnq8G5Y4OZt
          xNQzjg==
          -----END CERTIFICATE-----
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubedb
  syncPolicy:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - FailOnSharedResource=true
      # - RespectIgnoreDifferences=true
