apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  name: kubestash-appscode-com-snapshot
spec:
  targetRef:
    apiVersion: storage.kubestash.com/v1alpha1
    kind: Snapshot
  commonLabels:
  - key: invoker_kind
    value: "Snapshot"
  - key: invoker_name
    valuePath: .metadata.name
  - key: target_kind
    valuePath: .spec.appRef.kind
  - key: target_name
    valuePath: .spec.appRef.name
  - key: target_namespace
    valuePath: .spec.appRef.namespace
  metrics:
  - name: created
    help: "Unix creation timestamp of this Snapshot object"
    type: gauge
    field:
      path: .metadata.creationTimestamp
      type: DateTime
    metricValue:
      valueFromPath: .metadata.creationTimestamp
  - name: info
    help: "General information about this Snapshot"
    type: gauge
    labels:
    - key: snapshot_type
      valuePath: .spec.type
    - key: repository
      valuePath: .spec.repository
    - key: session
      valuePath: .spec.session
    - key: backupsession
      valuePath: .spec.backupSession
    - key: version
      valuePath: .spec.version
    - key: phase
      valuePath: .status.phase
    - key: integrity
      valuePath: .status.integrity
    metricValue:
      value: 1
  - name: phase
    help: "Snapshot object current phase"
    type: gauge
    field:
      path: .status.phase
      type: String
    params:
    - key: phase
      valuePath: .status.phase
    states:
      labelKey: phase
      values:
      - labelValue: Pending
        metricValue:
          valueFromExpression: "int(phase == 'Pending')"
      - labelValue: Running
        metricValue:
          valueFromExpression: "int(phase == 'Running')"
      - labelValue: Succeeded
        metricValue:
          valueFromExpression: "int(phase == 'Succeeded')"
      - labelValue: Failed
        metricValue:
          valueFromExpression: "int(phase == 'Failed')"
  - name: size_bytes
    help: "Size of this Snapshot"
    type: gauge
    field:
      path: .status.size
      type: String
    params:
    - key: size
      valuePath: .status.size
    metricValue:
      valueFromExpression: "bytes(size)"
  - name: time_seconds
    help: "The time when this Snapshot was taken"
    type: gauge
    field:
      path: .status.snapshotTime
      type: DateTime
    metricValue:
      valueFromPath: .status.snapshotTime
  - name: component_count_total
    help: "The number of total components for this Snapshot"
    type: gauge
    field:
      path: .status.totalComponents
      type: Integer
    metricValue:
      valueFromPath: .status.totalComponents
  - name: conditions
    help: "Current conditions of this Snapshot"
    type: gauge
    field:
      path: .status.conditions
      type: Array
    labels:
    - key: condition
      valuePath: .status.conditions[*].type
    - key: status
      valuePath: .status.conditions[*].status
    metricValue:
      value: 1

