apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sidekick.fullname" . }}
  labels:
    {{- include "sidekick.labels" . | nindent 4 }}
rules:
- apiGroups:
    - apps.k8s.appscode.com
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
