{{ if .Values.volumesnapshot.enabled }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'volumesnapshot-backup'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --volume-snapshot-class-name=${volumeSnapshotClassName:=}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubestash/volume-snapshotter")
    $) }}:v0.15.0'
{{ end }}

