# Default values for kubestash.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # License for the product.
  # Get a license by following the steps from [here](https://kubestash.com/docs/latest/setup/install/enterprise#get-a-trial-license).
  # Example:
  # helm install appscode/kubestash \
  #   --set-file global.license=/path/to/license/file
  # or
  # helm install appscode/kubestash \
  #   --set global.license=<license file content>
  license: ""
  # Docker registry used to pull Stash operator image
  registry: ""
  # Docker registry fqdn used to pull Stash related images.
  # Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
  registryFQDN: ""
  # Specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  #
  # Example:
  # helm template charts/kubestash \
  #   --set global.imagePullSecrets[0].name=sec0 \
  #   --set global.imagePullSecrets[1].name=sec1
  imagePullSecrets: []
  # Skip generating cleaner job YAML
  skipCleaner: false

  # Controls the network policy creation
  networkPolicy:
    enabled: false

# Pass values to kubestash-operator chart
kubestash-operator:
  enabled: true
kubestash-catalog:
  enabled: true
kubestash-metrics:
  enabled: true
ace-user-roles:
  # If enabled, installs the ace-user-roles chart
  enabled: true
  enableClusterRoles:
    ace: false
    appcatalog: true
    catalog: false
    cert-manager: false
    kubedb: false
    kubedb-ui: false
    kubestash: true
    kubevault: false
    license-proxyserver: true
    metrics: true
    prometheus: false
    stash: false
