apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns-monitoring.yaml

helmCharts:
- name: panopticon
  includeCRDs: true
  valuesInline:
    ace-user-roles:
      enabled: false
    monitoring:
      agent: prometheus.io/operator
      enabled: true
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
  releaseName: panopticon
  namespace: monitoring
  version: v2024.11.8
  repo: oci://ghcr.io/appscode-charts

patches:
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  patch: |
    - op: add
      path: "/metadata/annotations/config.kubernetes.io~1local-config"
      value: "true"
