{{- if dig "metrics" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:metrics:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - metrics.appscode.com
  resources:
  - "*"
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:metrics:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - metrics.appscode.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]

{{- end }}
