apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "petset.fullname" . }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "petset.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "petset.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
